
query:
  redis:
    nodes:
      - 10.19.132.217:7000
      - 10.19.132.217:7001
      - 10.19.132.217:7002
    password:
#spring:
#  redis:
#    jedis:
#      pool:
#        max-active:
server:
  port: 80
